# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Darin Webb
email: darinlwebb@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm an experienced system administrator and neophyte software developer
  with an interest in the science of IT operations and in ensuring that
  technology is a core competency serving you and your organization's goals.

  I also study, perform, and teach improv theatre with some of the most
  talented people in Des Moines.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.darinlwebb.com" # the base hostname & protocol for your site
twitter_username: Cat5InTheCradle
github_username:  Cat5InTheCradle

# Build settings
markdown: kramdown
